import 'package:aa_test/model/custom_song.dart';

var SONG8 = {
  5: OptionMadi(
      id: 5,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: true,
            leng: 1000,
            verticalIndex: 1,
            horihontalPos: 1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest1000.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 1000,
            verticalIndex: 1,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 2,
            horihontalPos: 24 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 2,
            horihontalPos: 33 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
      ]),
};
