import 'package:aa_test/model/custom_song.dart';

var SONG18 = {
  6: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 7,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 27 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  8: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 10,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 27 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  14: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 7,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 27 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  16: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 10,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 27 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  27: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 9,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 4,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 6,
            horihontalPos: 27 / 40,
            accType: 2,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  35: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 5,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 7,
            horihontalPos: 7 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 2,
            horihontalPos: 27 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  43: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 9,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 4,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 6,
            horihontalPos: 27 / 40,
            accType: 2,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
  51: OptionMadi(
      id: 4,
      rhythmUpper: 3,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 5,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 7,
            horihontalPos: 7 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 2,
            horihontalPos: 27 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 14 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
      ]),
};
