import 'package:aa_test/model/custom_song.dart';

var SONG50 = {
  4: OptionMadi(
      id: 2,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 9,
            horihontalPos: 0.1 / 40,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 1,
            isRest: false,
            leng: 250,
            verticalIndex: 12,
            horihontalPos: 5 / 40,
            assetName: "note250_2_81.svg"),
        OptionNote(
            id: 2,
            isRest: false,
            leng: 250,
            verticalIndex: 10,
            horihontalPos: 7.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 3,
            isRest: false,
            leng: 250,
            verticalIndex: 8,
            horihontalPos: 10 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 4,
            isRest: false,
            leng: 250,
            verticalIndex: 7,
            horihontalPos: 12.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 5,
            isRest: false,
            leng: 250,
            verticalIndex: 6,
            horihontalPos: 15 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 6,
            isRest: false,
            leng: 250,
            verticalIndex: 7,
            horihontalPos: 17.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 7,
            isRest: false,
            leng: 750,
            verticalIndex: 6,
            horihontalPos: 20 / 40,
            assetName: "note750_2.svg"),
        OptionNote(
            id: 8,
            isRest: false,
            leng: 250,
            verticalIndex: 5,
            horihontalPos: 28 / 40,
            assetName: "note250.svg"),
        OptionNote(
            id: 9,
            isRest: false,
            leng: 1000,
            verticalIndex: 4,
            horihontalPos: 30 / 40,
            assetName: "note1000.svg"),
      ]),
  5: OptionMadi(
      id: 2,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: true,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 2000,
            verticalIndex: NP.G2.index,
            horihontalPos: 0.1 / 40,
            assetName: "note2000_2.svg"),
        OptionNote(
            id: 1,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 20 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 2,
            isRest: false,
            leng: 250,
            verticalIndex: NP.E2.index,
            horihontalPos: 22.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 3,
            isRest: false,
            leng: 250,
            verticalIndex: NP.B1.index,
            accType: -1,
            horihontalPos: 25 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 4,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 27.5 / 40,
            assetName: "note250.svg"),
        OptionNote(
            id: 5,
            isRest: false,
            leng: 250,
            verticalIndex: NP.D2.index,
            horihontalPos: 30 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 6,
            isRest: false,
            leng: 250,
            verticalIndex: NP.C2.index,
            accType: 1,
            horihontalPos: 32.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 7,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G2.index,
            horihontalPos: 35 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 8,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 37.5 / 40,
            assetName: "note250_2.svg"),
      ]),
  6: OptionMadi(
      id: 4,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 2000,
            verticalIndex: NP.F2.index,
            horihontalPos: 0.1 / 40,
            assetName: "note2000_2.svg"),
        OptionNote(
            id: 1,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 20 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 2,
            isRest: false,
            leng: 250,
            verticalIndex: NP.D2.index,
            horihontalPos: 22.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 3,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 25 / 40,
            assetName: "note250.svg"),
        OptionNote(
            id: 4,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G1.index,
            horihontalPos: 27.5 / 40,
            assetName: "note250.svg"),
        OptionNote(
            id: 5,
            isRest: false,
            leng: 250,
            verticalIndex: NP.C2.index,
            horihontalPos: 30 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 6,
            isRest: false,
            leng: 250,
            verticalIndex: NP.B1.index,
            horihontalPos: 32.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 7,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 35 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 8,
            isRest: false,
            leng: 250,
            verticalIndex: NP.E2.index,
            horihontalPos: 37.5 / 40,
            assetName: "note250_2.svg"),
      ]),
  9: OptionMadi(
      id: 7,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: true,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.B1.index,
            horihontalPos: 0.1 / 40,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 1,
            isRest: false,
            leng: 250,
            verticalIndex: NP.B1.index,
            horihontalPos: 10 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 2,
            isRest: false,
            leng: 125,
            verticalIndex: NP.C2.index,
            horihontalPos: 12.5 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 3,
            isRest: false,
            leng: 125,
            verticalIndex: NP.B1.index,
            horihontalPos: 14 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 4,
            isRest: false,
            leng: 125,
            verticalIndex: NP.A1.index,
            horihontalPos: 15.5 / 40,
            assetName: "note125.svg"),
        OptionNote(
            id: 5,
            isRest: false,
            leng: 125,
            verticalIndex: NP.B1.index,
            horihontalPos: 17 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 6,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G1.index,
            horihontalPos: 18.5 / 40,
            assetName: "note250.svg"),
        OptionNote(
            id: 7,
            isRest: false,
            leng: 1500,
            verticalIndex: NP.G2.index,
            horihontalPos: 21 / 40,
            assetName: "note1500_2.svg"),
        OptionNote(
            id: 8,
            isRest: false,
            leng: 500,
            verticalIndex: NP.B1.index,
            accType: -1,
            horihontalPos: 35 / 40,
            assetName: "note500_2.svg"),
      ]),
  10: OptionMadi(
      id: 7,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.A1.index,
            horihontalPos: -0.5 / 40,
            assetName: "note500.svg"),
        OptionNote(
            id: 1,
            isRest: false,
            leng: 750,
            verticalIndex: NP.A2.index,
            horihontalPos: 5 / 40,
            assetName: "note750_2_81.svg"),
        OptionNote(
            id: 2,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G2.index,
            horihontalPos: 12.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 3,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 15 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 4,
            isRest: false,
            leng: 250,
            verticalIndex: NP.E2.index,
            horihontalPos: 17.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 5,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.F2.index,
            horihontalPos: 20 / 40,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 6,
            isRest: false,
            leng: 125,
            verticalIndex: NP.F2.index,
            horihontalPos: 30 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 7,
            isRest: false,
            leng: 125,
            verticalIndex: NP.E2.index,
            horihontalPos: 31.25 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 8,
            isRest: false,
            leng: 125,
            verticalIndex: NP.D2.index,
            horihontalPos: 32.5 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 9,
            isRest: false,
            leng: 125,
            verticalIndex: NP.C2.index,
            horihontalPos: 33.75 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 10,
            isRest: false,
            leng: 250,
            verticalIndex: NP.B1.index,
            horihontalPos: 35 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 11,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 37.5 / 40,
            assetName: "note250.svg"),
      ]),
  13: OptionMadi(
      id: 11,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: true,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.C2.index,
            horihontalPos: 0.1 / 40,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 1,
            isRest: false,
            leng: 250,
            verticalIndex: NP.C2.index,
            horihontalPos: 10 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 2,
            isRest: false,
            leng: 250,
            verticalIndex: NP.E2.index,
            horihontalPos: 12.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 3,
            isRest: false,
            leng: 250,
            verticalIndex: NP.D2.index,
            horihontalPos: 15 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 4,
            isRest: false,
            leng: 250,
            verticalIndex: NP.C2.index,
            horihontalPos: 17.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 5,
            isRest: false,
            leng: 1500,
            verticalIndex: NP.A2.index,
            horihontalPos: 20 / 40,
            assetName: "note1500_2_81.svg"),
        OptionNote(
            id: 6,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G2.index,
            horihontalPos: 35 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 7,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            accType: 1,
            horihontalPos: 37.5 / 40,
            assetName: "note250_2.svg"),
      ]),
  17: OptionMadi(
      id: 15,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: true,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.G1.index,
            horihontalPos: 0.1 / 40,
            assetName: "note1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G1.index,
            horihontalPos: 10 / 40,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.B1.index,
            horihontalPos: 12.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.D2.index,
            horihontalPos: 15 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 17.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.F2.index,
            horihontalPos: 20 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.D2.index,
            horihontalPos: 22.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.E2.index,
            horihontalPos: 25 / 40,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.E2.index,
            horihontalPos: 32.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 125,
            verticalIndex: NP.F2.index,
            horihontalPos: 35 / 40,
            assetName: "note125_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 125,
            verticalIndex: NP.G2.index,
            horihontalPos: 37.5 / 40,
            assetName: "note125_2.svg"),
      ]),
  18: OptionMadi(
      id: 16,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.C2.index,
            horihontalPos: 0.1 / 40,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.C2.index,
            horihontalPos: 10 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.E2.index,
            horihontalPos: 12.5 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.G2.index,
            horihontalPos: 15 / 40,
            assetName: "note250_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.B2.index,
            accType: -1,
            horihontalPos: 17.5 / 40,
            assetName: "note250_2_83.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.B2.index,
            horihontalPos: 20 / 40,
            assetName: "note500_2_83.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.A2.index,
            horihontalPos: 25 / 40,
            assetName: "note1000_2_81.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.C2.index,
            horihontalPos: 35 / 40,
            assetName: "note500_2.svg"),
      ]),
};
