import 'package:aa_test/model/custom_song.dart';

var SONG46 = {
  43: OptionMadi(
      id: 4,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 333,
            verticalIndex: NP.C2.index,
            horihontalPos: 0 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            assetName: "note333.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 333,
            verticalIndex: NP.B1.index,
            horihontalPos: 6 / 40,
            accType: 0,
            articType: 0,
            is3Shown: true,
            parType: 0,
            assetName: "note333.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 333,
            verticalIndex: NP.A1.index,
            horihontalPos: 12 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            assetName: "note333.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.G1.index,
            horihontalPos: 18 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 1,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.F1.index,
            horihontalPos: 24 / 40,
            accType: 0,
            articType: 0,
            is3Shown: true,
            parType: 0,
            assetName: "note750.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.E1.index,
            horihontalPos: 30 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 2,
            assetName: "note250.svg"),
      ]),
  4: OptionMadi(
      id: 4,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: true,
            leng: 1000,
            verticalIndex: 2,
            horihontalPos: 1 / 20,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 8,
            horihontalPos: 10 / 20,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 7,
            horihontalPos: 15 / 20,
            accType: 1,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
      ]),
  8: OptionMadi(
      id: 8,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.E1.index,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 500,
            verticalIndex: 2,
            horihontalPos: 10 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.D2.index,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.C2.index,
            horihontalPos: 30 / 40,
            accType: 1,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
      ]),
  16: OptionMadi(
      id: 8,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.E1.index,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),

        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.D2.index,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.C2.index,
            horihontalPos: 30 / 40,
            accType: 1,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
      ]),
  12: OptionMadi(
      id: 8,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: NP.D1.index,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),

        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.D2.index,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.C2.index,
            horihontalPos: 30 / 40,
            accType: 1,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500_2.svg"),
      ]),
  6: OptionMadi(
      id: 8,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.A1.index,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 10 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 15 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.G1.index,
            horihontalPos: 20 / 40,
            accType: 1,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.G1.index,
            horihontalPos: 30 / 40,
            accType: 2,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
      ]),
  14: OptionMadi(
      id: 14,
      rhythmUpper: 2,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: -1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 5 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 250,
            verticalIndex: NP.D2.index,
            horihontalPos: 11 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: NP.A1.index,
            horihontalPos: 15 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.G1.index,
            horihontalPos: 20 / 40,
            accType: 1,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: NP.G1.index,
            horihontalPos: 30 / 40,
            accType: 2,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note500.svg"),
      ]),
};
