import 'package:aa_test/model/custom_song.dart';

var SONG5 = {
  5: OptionMadi(
      id: 5,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 8,
            horihontalPos: 0.5 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 3000,
            verticalIndex: 3,
            horihontalPos: 10 / 20,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest3000.svg"),
      ]),
  7: OptionMadi(
      id: 5,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 8,
            horihontalPos: 0.5 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 3000,
            verticalIndex: 3,
            horihontalPos: 10 / 20,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest3000.svg"),
      ]),
  21: OptionMadi(
      id: 5,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: true,
      isClefShown: true,
      isTempoShown: false,
      scale: 1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 8,
            horihontalPos: 0.5 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 3000,
            verticalIndex: 3,
            horihontalPos: 10 / 20,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest3000.svg"),
      ]),
  23: OptionMadi(
      id: 5,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 1,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 8,
            horihontalPos: 0.5 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 3000,
            verticalIndex: 3,
            horihontalPos: 10 / 20,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest3000.svg"),
      ]),
};
