import 'package:aa_test/model/custom_song.dart';

var SONG10 = {
  5: pt5_17,
  9: pt5_17,
  17: pt5_17,
  11: OptionMadi(
      id: 11,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 4,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 750,
            verticalIndex: 2,
            horihontalPos: 7 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note750.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: 0,
            horihontalPos: 12 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 1,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 1,
            horihontalPos: 30 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
      ]),
  19: OptionMadi(
      id: 19,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 0,
      endType: 0,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 4,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 750,
            verticalIndex: 2,
            horihontalPos: 7 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note750.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 250,
            verticalIndex: 0,
            horihontalPos: 12 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note250.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 1,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 1,
            horihontalPos: 30 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
      ]),
};

var pt5_17 = OptionMadi(
    id: 0,
    rhythmUpper: 4,
    rhythmUnder: 4,
    isRhythmShown: false,
    isScaleShown: true,
    isClefShown: true,
    isTempoShown: false,
    scale: 0,
    endType: 0,
    notes: [
      // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
      OptionNote(
          id: 0,
          isRest: false,
          leng: 1000,
          verticalIndex: NP.E1.index,
          horihontalPos: 0.1 / 60,
          assetName: "note1000.svg"),
      OptionNote(
          id: 0,
          isRest: false,
          leng: 500,
          verticalIndex: NP.D1.index,
          horihontalPos: 20 / 60,
          assetName: "note500.svg"),
      OptionNote(
          id: 0,
          isRest: false,
          leng: 500,
          verticalIndex: NP.C1.index,
          horihontalPos: 30 / 60,
          assetName: "note500.svg"),
      OptionNote(
          id: 0,
          isRest: false,
          leng: 500,
          verticalIndex: NP.E1.index,
          horihontalPos: 40 / 60,
          assetName: "note500.svg"),
      OptionNote(
          id: 0,
          isRest: false,
          leng: 500,
          verticalIndex: NP.D1.index,
          horihontalPos: 50 / 60,
          assetName: "note500.svg"),
    ]);
