import 'package:aa_test/model/custom_song.dart';

var SONG35 = {
  20: OptionMadi(
      id: 40,
      rhythmUpper: 4,
      rhythmUnder: 4,
      isRhythmShown: false,
      isScaleShown: false,
      isClefShown: false,
      isTempoShown: false,
      scale: 1,
      endType: 2,
      notes: [
        // id,isRest,leng,verticalIndex,horihontalPos,accType,articType,is3Shown,parType,assetName
        OptionNote(
            id: 0,
            isRest: false,
            leng: 1000,
            verticalIndex: 5,
            horihontalPos: 0.1 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 9,
            horihontalPos: 10 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 10 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 12,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 1,
            is3Shown: false,
            parType: 0,
            assetName: "note1000_2.svg"),
        OptionNote(
            //fake
            id: 0,
            isRest: false,
            leng: 500,
            verticalIndex: 3,
            horihontalPos: 20 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "opa.svg"),
        OptionNote(
            id: 0,
            isRest: true,
            leng: 1000,
            verticalIndex: 2,
            horihontalPos: 30 / 40,
            accType: 0,
            articType: 0,
            is3Shown: false,
            parType: 0,
            assetName: "rest1000.svg"),
      ]),
};
